config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
=begin   get 'relacion_libros/index'
  get 'relacion_libros/show'
  get 'relacion_libros/edit'
  get 'bibliotecas/index'
  get 'bibliotecas/show'
  get 'bibliotecas/edit'
  get 'libros/index'
  get 'libros/show'
  get 'libros/edit'
  get 'autors/index'
  get 'autors/show'
  get 'autors/edit'
=end
  root "bibliotecas#index"

  resources :autors, :libros, :bibliotecas, :relacion_libros,:editorials, :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/biblioteca.rb
class Biblioteca < ApplicationRecord
    has_many :relacion_libros
end

app/controllers/bibliotecas_controller.rb
class BibliotecasController < ApplicationController
  before_action :authenticate_user!
  def index
    
    @biblioteca=Biblioteca.all

  end

  def show
    @biblioteca=Biblioteca.find(params[:id])
    # @relacionlibros=RelacionLibro.where("biblioteca_id=?",params[:id])
    @relacionlibros=RelacionLibro.where(biblioteca_id:params[:id])
  end

  def new
    @biblioteca=Biblioteca.new
  end
  def create
    @biblioteca=Biblioteca.new(
      nombre:params[:biblioteca][:nombre],
      direccion:params[:biblioteca][:direccion]
    )
    if @biblioteca.save
        redirect_to bibliotecas_path
    else
      render :new
    end

  end
   
  def edit
    @biblioteca=Biblioteca.find(params[:id])
  end

  def update  
      @biblioteca=Biblioteca.find(params[:id])
      if @biblioteca.update(
        nombre:params[:biblioteca][:nombre],
        direccion:params[:biblioteca][:direccion]
        )
        redirect_to bibliotecas_path
      else
        render :edit
      end
  end 

  def params_biblioteca
    params.require(:biblioteca).permit(:nombre, :direccion)

  end

  def destroy
    @biblioteca=Biblioteca.find(params[:id])
    @biblioteca.destroy
    redirect_to bibliotecas_path
  end  
  
end

app/helpers/bibliotecas_helper.rb
module BibliotecasHelper
end

app/views/bibliotecas/edit.html.erb
<h1>Bibliotecas#edit</h1>
<p>Find me in app/views/bibliotecas/edit.html.erb</p>


<h1>Modificar biblioteca nueva</h1>

<br>
<br>
<%= form_for (@biblioteca) do |b|%>
    <label>Nombre:</label>
    <%= b.text_field :nombre %>
    <br>
    <label>Dirección:</label>
    <%= b.text_field :direccion %>
    <br>
    <br>
    <%= b.submit "Guardar cambios", :class =>"btn btn-primary" %>
<% end %> 

app/views/bibliotecas/index.html.erb
<style>
    .table{
        width: 90%;
        margin:auto;
    }

    
    
    
</style>
<br>
<h1>Bibliotecas</h1>
<%# <p>Find me in app/views/bibliotecas/index.html.erb</p> %>
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <h5 class="text-white h4">Collapsed content</h5>
    <span class="text-muted">Toggleable via the navbar brand.</span>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

<%= link_to "Cerrar sesi&oacuten", destroy_user_session_path,class: :"btn btn-primary", method: :delete%>
<%# @libro=Libro.find(1) %>
<%# @libro.autor.nombre %>


<%# image_tag("library.png",size:"250x250",alt: :"Servicios de Salud de S.L.P." ) %>

<br>

<br>


<section>
<h3>Lista de bibliotecas:</h3>
<br>
<table class="table">
<thead>
    <tr>
        <th>Nombre</th>
        <th>Dirección</th>
        <th>Show</th>
        <th>Editar</th>
        <th>Borrar</th>
    </tr>
</thead>
<tbody>
           
        <% @biblioteca.each do |b| %>
            <tr>
                <td><%= b.nombre%>   </td>
                <td><%= b.direccion%>   </td>
                <td> <%= link_to "Show", biblioteca_path(b.id), 
                        :class => "btn btn-primary"%>
                </td>
                <td> <%= link_to raw("#{image_tag("pencil_icon.svg",size:"25x25",alt: :"edit", style: :"color:white;" )} Modificar"), edit_biblioteca_path(b.id), 
                        :class => "btn btn-primary"
                        %>
                </td>
                <td> 
                    <%= link_to "Eliminar", 
                        biblioteca_path(b.id), 
                        data:{:confirm =>"Deseas eliminar?"},
                        method: :delete, 
                        :class => "btn btn-danger" %>
                </td>
            </tr>
        <% end %>
</tbody>
</table>
</section>

app/views/bibliotecas/new.html.erb
<h1>Agregar biblioteca nueva</h1>

<br>
<br>
<%= form_for (@biblioteca) do |b|%>
    <label>Nombre:</label>
    <%= b.text_field :nombre %>
    <br>
    <label>Dirección:</label>
    <%= b.text_field :direccion %>
    <br>
    <%= b.submit "Guardar", :class =>"btn btn-success" %>
<% end %>    

app/views/bibliotecas/show.html.erb
<h1>Bibliotecas#show</h1>
<%# <p>Find me in app/views/bibliotecas/show.html.erb</p> %>


<%= link_to "Nueva Biblioteca", new_biblioteca_path, :class => "btn btn-primary" %>
<%= link_to 'Nuevo Autor', new_autor_path, :class => "btn btn-primary" %>
<%= link_to 'Nuevo Libro', new_libro_path, :class => "btn btn-primary" %>
<%= link_to 'Agregar libro a biblioteca', new_relacion_libro_path, :class => "btn btn-primary" %>

<br>

<br>

<style>
    .table{
        width: 85%;
        margin:auto;
    }
</style>
<section>
<h3>Lista de libros de la biblioteca: <%= @biblioteca.nombre%></h3>
<br>
<table class="table table-striped">
<thead>
    <tr>
        <td>Biblioteca</td>
        <td>Libro</td>
        <td>Editar</td>
        <td>Borrar</td>
    </tr>
</thead>
<tbody>
           
        <% @relacionlibros.each do |r| %>
            <tr>
                <td><%= r.biblioteca.nombre%>   </td>
                <td><%= r.libro.titulo%>   </td>
                <td> <%= link_to "Modificar", edit_biblioteca_path(r.biblioteca_id), 
                        :class => "btn btn-primary"%>
                </td>
                <td> 
                    <%= link_to "Eliminar", 
                        biblioteca_path(r.biblioteca_id), 
                        data:{:confirm =>"Deseas eliminar?"},
                        method: :delete, 
                        :class => "btn btn-danger" %>
                </td>
            </tr>
        <% end %>
</tbody>
</table>
</section>