config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
=begin   get 'relacion_libros/index'
  get 'relacion_libros/show'
  get 'relacion_libros/edit'
  get 'bibliotecas/index'
  get 'bibliotecas/show'
  get 'bibliotecas/edit'
  get 'libros/index'
  get 'libros/show'
  get 'libros/edit'
  get 'autors/index'
  get 'autors/show'
  get 'autors/edit'
=end
  root "bibliotecas#index"

  resources :autors, :libros, :bibliotecas, :relacion_libros,:editorials, :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/libro.rb
class Libro < ApplicationRecord
  belongs_to :autor
  has_many :relacion_libros
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  def index
  end

  def show
  end

  def new
    @libro=Libro.new
    @autor=Autor.all
  end
  def create
    @libro=Libro.new(
      titulo:params[:libro][:titulo],
      autor_id:params[:libro][:autor_id],
      isbn:params[:libro][:isbn],
      editorial:params[:libro][:editorial],
      edicion:params[:libro][:edicion],
      precio:params[:libro][:precio]
      
    )
    if @libro.save
        UserMailer.new_libro(current_user, @libro).deliver  
        redirect_to libros_path

    else
      render :new
    end

  end

  def edit
  end


end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/libros/edit.html.erb
<h1>Libros#edit</h1>
<p>Find me in app/views/libros/edit.html.erb</p>

app/views/libros/index.html.erb
<h1>Libros#index</h1>
<p>Find me in app/views/libros/index.html.erb</p>

<%= link_to 'Bibliotecas', bibliotecas_path %>

app/views/libros/new.html.erb
<h1>Agregar libro nuevo</h1>

<br>
<br>
<%= form_for (@libro) do |l|%>
    <label>Título:</label>
    <%= l.text_field :titulo %>
    <br>
    <label>Autor:</label>
    <%= l.select(:autor_id, "",{},{}) do %>
    <%= options_from_collection_for_select(@autor, :id, :nombre) %>
    <% end %>        
    <br>
    <%= l.submit "Guardar", :class =>"btn btn-success" %>
<% end %>    

app/views/libros/show.html.erb
<h1>Libros#show</h1>
<p>Find me in app/views/libros/show.html.erb</p>