config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
=begin   get 'relacion_libros/index'
  get 'relacion_libros/show'
  get 'relacion_libros/edit'
  get 'bibliotecas/index'
  get 'bibliotecas/show'
  get 'bibliotecas/edit'
  get 'libros/index'
  get 'libros/show'
  get 'libros/edit'
  get 'autors/index'
  get 'autors/show'
  get 'autors/edit'
=end
  root "bibliotecas#index"

  resources :autors, :libros, :bibliotecas, :relacion_libros,:editorials, :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/editorial.rb
class Editorial < ApplicationRecord
end

app/controllers/editorials_controller.rb
class EditorialsController < ApplicationController
  before_action :set_editorial, only: %i[ show edit update destroy ]

  # GET /editorials or /editorials.json
  def index
    @editorials = Editorial.all
  end

  # GET /editorials/1 or /editorials/1.json
  def show
  end

  # GET /editorials/new
  def new
    @editorial = Editorial.new
  end

  # GET /editorials/1/edit
  def edit
  end

  # POST /editorials or /editorials.json
  def create
    @editorial = Editorial.new(editorial_params)

    respond_to do |format|
      if @editorial.save
        format.html { redirect_to @editorial, notice: "Editorial was successfully created." }
        format.json { render :show, status: :created, location: @editorial }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @editorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /editorials/1 or /editorials/1.json
  def update
    respond_to do |format|
      if @editorial.update(editorial_params)
        format.html { redirect_to @editorial, notice: "Editorial was successfully updated." }
        format.json { render :show, status: :ok, location: @editorial }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @editorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editorials/1 or /editorials/1.json
  def destroy
    @editorial.destroy
    respond_to do |format|
      format.html { redirect_to editorials_url, notice: "Editorial was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_editorial
      @editorial = Editorial.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def editorial_params
      params.require(:editorial).permit(:nombre, :direccion, :numero)
    end
end

app/helpers/editorials_helper.rb
module EditorialsHelper
end

app/views/editorials/_form.html.erb
<%= form_with(model: editorial) do |form| %>
  <% if editorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(editorial.errors.count, "error") %> prohibited this editorial from being saved:</h2>

      <ul>
        <% editorial.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_field :direccion %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.number_field :numero %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/editorials/edit.html.erb
<h1>Editing Editorial</h1>

<%= render 'form', editorial: @editorial %>

<%= link_to 'Show', @editorial %> |
<%= link_to 'Back', editorials_path %>

app/views/editorials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Editoriales</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Numero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @editorials.each do |editorial| %>
      <tr>
        <td><%= editorial.nombre %></td>
        <td><%= editorial.direccion %></td>
        <td><%= editorial.numero %></td>
        <td><%= link_to 'Show', editorial %></td>
        <td><%= link_to 'Edit', edit_editorial_path(editorial) %></td>
        <td><%= link_to 'Destroy', editorial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Editorial', new_editorial_path %>

app/views/editorials/new.html.erb
<h1>New Editorial</h1>

<%= render 'form', editorial: @editorial %>

<%= link_to 'Back', editorials_path %>

app/views/editorials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @editorial.nombre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @editorial.direccion %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @editorial.numero %>
</p>

<%= link_to 'Edit', edit_editorial_path(@editorial) %> |
<%= link_to 'Back', editorials_path %>